"""Localized help and privacy content for the same static templates."""
from pathlib import Path
from build import C, ROOT, BASE, page, faq_html

CONTACT='<p>Sascha Bommels<br>Flandernstr. 18<br>46147 Oberhausen<br>Deutschland / Germany<br><a href="mailto:stockscansupport@gmail.com">stockscansupport@gmail.com</a></p>'
DOCS={
'de':{
 'support_title':'Wie können wir helfen?', 'support_intro':'Die wichtigsten Handgriffe für StockScan 1.4. Direkt zum nächsten Scan.',
 'help':[
  ['Wie starte ich eine freie oder feste Inventur?','Öffne „Listen“ und lege eine neue Inventur an. Für eine feste Inventur wählst du eine Artikelvorgabe aus XLSX, CSV oder TSV aus. Das geht auch in „Daten“ über „Feste Inventur aus Datei“. Prüfe die Vorschau und erstelle anschließend die Liste.'],
  ['Wie übernehme ich meinen Artikelstamm?','Öffne „Daten“ → „Produkt-Stammdaten“ und wähle deine XLSX- oder CSV-Datei. Die Datei benötigt eine EAN oder Artikelnummer; Namen und Einheiten können ergänzt werden. Prüfe die Vorschau vor dem Import. Hersteller und Lieferanten übernimmst du separat über „Hersteller-Zuordnungen“.'],
  ['Warum lässt sich die feste Inventur nicht abschließen?','Jeder Vorgabeartikel muss gezählt oder ausdrücklich übersprungen sein. Öffne „Vorgabeartikel prüfen“, zähle offene Artikel nach oder überspringe sie bewusst. Eine gezählte Menge von null ist etwas anderes als ein übersprungener Artikel.'],
  ['Wie verwende ich dieselbe Vorgabe erneut?','Wähle im Menü der festen Inventur „Zählungen zurücksetzen“ und bestätige die Aktion. Die feste Vorgabe bleibt erhalten. Mengen, Kommentare und Überspringen-Entscheidungen werden zurückgesetzt; zusätzliche Positionen werden entfernt. Sichere bei Bedarf vorher deinen Bericht.'],
  ['Wie exportiere ich meinen Bestand?','Öffne „Daten“, wähle die gewünschte Exportliste und danach das Exportformat. CSV ist kostenlos und unbegrenzt verfügbar. Mit Pro kannst du angereicherte Excel-Dateien (.xlsx) erstellen. Über das System-Teilen-Menü speicherst oder teilst du die Datei.'],
  ['Wie berechne ich Mengen und behandle doppelte Scans?','Gib beim Erfassen einen Ausdruck wie 7 × 8 ein; StockScan berechnet 56. Bei einem erneut erfassten Artikel kannst du die Menge addieren oder ersetzen. Kontrolliere dabei die gewählte Einheit. Pro Fast Scan unterstützt einstellbare direkte Zählschritte.'],
  ['Die Kamera erkennt den Code nicht. Was hilft?','Prüfe in den iOS-Einstellungen die Kameraberechtigung für StockScan. Beleuchte den vollständigen Code gleichmäßig und halte die Kamera ruhig. Du kannst Artikelnummern in „Erfassen“ auch manuell eingeben.'],
  ['Wie nutze ich die Apple Watch?','Wähle auf dem iPhone einen Artikel zum Zählen auf der gekoppelten Watch. Pro kann über die Listenaktion „Zählliste an Watch senden“ eine ganze Inventurliste übertragen. Lass die Geräte die ausstehenden Zählungen synchronisieren, bevor du die Inventur abschließt.'],
  ['Wie aktiviere ich iCloud?','Öffne die Einstellungen und den Bereich für iCloud-Synchronisierung. Mit Pro kannst du sie freiwillig aktivieren. Verwende auf deinen eigenen Geräten dasselbe iCloud-Konto. Die Inventur bleibt lokal nutzbar; importierte Produkt- und Herstellerstammdaten synchronisieren nicht mit.'],
  ['Wie stelle ich Pro wieder her?','Öffne StockScan Pro in den Einstellungen und wähle „Käufe wiederherstellen“. Verwende das Apple-Konto des ursprünglichen Kaufs. Prüfe bei Family Sharing zusätzlich Apples Familieneinstellungen. Das Abo verwaltest du in deinen Apple-Account-Einstellungen.'],
 ],
 'contact_title':'Noch nicht gelöst?', 'contact_text':'Schreibe uns mit deiner App-Version, deinem Gerät und den Schritten, bei denen das Problem auftritt. Einen technischen Diagnosebericht kannst du in den Einstellungen freiwillig erstellen und vor dem Teilen prüfen. Sende nur Daten, die für deine Anfrage nötig sind.',
 'privacy_title':'Datenschutzerklärung','updated':'Stand: 13. September 2026',
 'privacy_intro':'StockScan speichert Inventuren lokal. Mit Pro ist private iCloud-Synchronisierung freiwillig zuschaltbar. Die App benötigt kein StockScan-Konto und verwendet keine Werbung oder Trackingdienste. Diese Erklärung beschreibt App, Website und Support.',
 'privacy_sections':[
  ['1. Verantwortliche Stelle',CONTACT],
  ['2. Inventur- und Stammdaten','<p>StockScan verarbeitet die von dir eingegebenen oder importierten Artikelcodes, EANs, Namen, Mengen, Einheiten, Kommentare, Zuordnungen und Zeitstempel. Dazu kommen Inventurlisten, feste Artikelvorgaben, Zähl- und Prüfstatus sowie abgeschlossene Inventuren und Vorlagen. Diese Daten werden lokal mit SwiftData gespeichert. Importierte Produkt-, Hersteller- und Lieferantenstammdaten bleiben auf dem jeweiligen Gerät.</p>'],
  ['3. Freiwillige private iCloud-Synchronisierung','<p>Wenn du die Pro-Synchronisierung ausdrücklich aktivierst, werden Inventuren über Apples CloudKit in der privaten Datenbank deines iCloud-Kontos zwischen deinen eigenen Apple-Geräten synchronisiert. StockScan betreibt dafür keinen eigenen Inventurdatenserver. Der lokale Datenstand bleibt die Grundlage. Importierte Stammdaten werden nicht synchronisiert.</p><p>Du kannst die Synchronisierung pausieren und die Cloud-Kopie über die dafür vorgesehene Funktion separat löschen. Ein Abo-Ablauf oder Verbindungsproblem löscht keine lokalen Daten. Das Entfernen der App löscht nicht automatisch die Cloud-Kopie. Die Verarbeitung durch Apple richtet sich auch nach deinen iCloud-Einstellungen und <a href="https://www.apple.com/legal/privacy/">Apples Datenschutzbestimmungen</a>.</p>'],
  ['4. Käufe und Apple Family Sharing','<p>Käufe, Wiederherstellungen und Aboberechtigungen werden nativ über Apple StoreKit verarbeitet. Apple wickelt die Zahlung ab; der Entwickler erhält keine Zahlungsdaten. Family Sharing teilt die Pro-Berechtigung, nicht deine Inventuren oder deine private iCloud-Datenbank. StockScan verwendet keinen externen Abonnementdienst.</p>'],
  ['5. Kamera, Apple Watch und Live Activities','<p>Der Kamerazugriff dient der Barcode-Erkennung. Dabei werden keine Kamerafotos gespeichert oder an den Entwickler übertragen. Ausgewählte Zähldaten werden über WatchConnectivity zwischen iPhone und gekoppelter Apple Watch ausgetauscht. Bei unterbrochener Verbindung bleiben ausstehende Watch-Zählungen bis zur Bestätigung gespeichert. Live Activities zeigen den Inventurfortschritt auf Systemoberflächen deines Geräts an.</p>'],
  ['6. Intelligente Importhilfe','<p>Auf unterstützten Geräten kann die intelligente Spaltenerkennung Apple Intelligence verwenden, wenn verfügbar. Die Spaltenerkennung der App erfolgt auf dem Gerät. Die normale Erkennung bleibt als Alternative erhalten. StockScan sendet dafür keine Tabellen an einen KI-Dienst des Entwicklers.</p>'],
  ['7. Exporte, Löschung und Gerätebackup','<p>Du entscheidest, wohin du CSV- oder XLSX-Dateien über das System-Teilen-Menü weitergibst. Für gewählte Ziel-Apps oder Dienste gelten deren Datenschutzbedingungen. Lokale Inventuren lassen sich in der App löschen. Beim Entfernen der App werden ihre lokalen Daten entfernt; sichere benötigte Daten vorher. Ein persönliches Gerätebackup kann App-Daten nach deinen Apple-Einstellungen enthalten. Gerätebackup und die freiwillige CloudKit-Synchronisierung sind unterschiedliche Funktionen.</p>'],
  ['8. Support und freiwillige Diagnoseberichte','<p>Wenn du uns per E-Mail kontaktierst, verarbeiten wir deine Absenderadresse und die von dir mitgeteilten Inhalte, um deine Anfrage zu bearbeiten. Ein technischer Diagnosebericht wird nur auf deine Initiative erstellt und geteilt. Er enthält technische App- und Geräteinformationen, Einstellungszustände sowie aggregierte Datenbankzahlen. Prüfe den Bericht vor dem Versenden und teile nur erforderliche Informationen.</p>'],
  ['9. Diese Website','<p>Diese Website wird über GitHub Pages bereitgestellt. Beim Abruf verarbeitet GitHub technisch notwendige Verbindungs- und Anfragedaten, beispielsweise IP-Adresse, Browserinformationen und Abrufzeit. Angaben zur Verarbeitung und internationalen Datenübermittlung findest du in <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHubs Datenschutzerklärung</a>.</p><p>Unsere Website bindet keine Analysewerkzeuge, Werbepixel oder externen Schriftarten ein und setzt selbst keine Cookies. Die Sprachwahl erfolgt über getrennte Seiten ohne Speicherung im Browser. Erst beim Öffnen eines externen Links, etwa zum App Store, rufst du den jeweiligen Dienst auf.</p>'],
  ['10. Deine Datenschutzanfragen','<p>Du kannst dich für Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit oder Widerspruch bezüglich personenbezogener Daten an uns wenden. Soweit eine Verarbeitung auf Einwilligung beruht, kannst du sie für die Zukunft widerrufen. Außerdem besteht das Recht auf Beschwerde bei einer Datenschutzaufsichtsbehörde. Bei ausschließlich lokal gespeicherten Inventuren erfolgt die Verwaltung direkt auf deinem Gerät; der Entwickler hat keinen Zugriff auf diese Inhalte.</p>'],
  ['11. Kontakt','<p>Bei Fragen zum Datenschutz: <a href="mailto:stockscansupport@gmail.com">stockscansupport@gmail.com</a></p>']
 ]
},
'en':{
 'support_title':'How can we help?','support_intro':'The essential steps for StockScan 1.4. Get back to your next scan.',
 'help':[
  ['How do I start a free or fixed inventory?','Open Lists and create a new inventory. For a fixed inventory, select a checklist in XLSX, CSV or TSV format. You can also use Fixed inventory from file in Data. Review the preview, then create your list.'],
  ['How do I import product data?','Open Data → Product master data and choose your XLSX or CSV file. It needs an EAN or item number; names and units can be added. Review the preview before importing. Import manufacturer and supplier mappings separately via Manufacturer mappings.'],
  ['Why can’t I complete a fixed inventory?','Every required item must be counted or explicitly skipped. Open the required-item review, count remaining items or choose to skip them. A counted quantity of zero is different from a skipped item.'],
  ['How do I reuse the same checklist?','Choose Reset counts from the fixed inventory menu and confirm. The checklist stays in place. Counts, comments and skip decisions are cleared; additional items are removed. Export your report beforehand if you need to keep it.'],
  ['How do I export inventory?','Open Data, select the list to export and choose an export format. CSV is free and unlimited. Pro adds enriched Excel (.xlsx) exports. Save or share the file using the system share sheet.'],
  ['How do calculations and duplicate scans work?','Enter an expression such as 7 × 8; StockScan calculates 56. When capturing an existing item, you can add to or replace its quantity. Check the selected unit. Pro Fast Scan supports configurable direct count steps.'],
  ['The camera isn’t recognising a code. What can I do?','Check StockScan’s camera permission in iOS Settings. Light the full code evenly and hold the camera steady. You can also enter an item number manually in Capture.'],
  ['How do I use Apple Watch?','Select an item on iPhone to count on your paired Watch. Pro can send an entire inventory using the list action Send count list to Watch. Let the devices sync pending counts before completing the inventory.'],
  ['How do I enable iCloud?','Open Settings and the iCloud sync section. With Pro, you can enable it voluntarily. Use the same iCloud account on your own devices. Inventories remain usable locally; imported product and manufacturer master data does not sync.'],
  ['How do I restore Pro?','Open StockScan Pro in Settings and choose Restore purchases. Use the Apple account that made the original purchase. For Family Sharing, also check Apple’s family settings. Manage your subscription in your Apple account settings.']
 ],
 'contact_title':'Still need a hand?','contact_text':'Email us with your app version, device and the steps that lead to the issue. You can voluntarily create a technical diagnostic report in Settings and review it before sharing. Only include information needed for your request.',
 'privacy_title':'Privacy policy','updated':'Updated: 13 September 2026',
 'privacy_intro':'StockScan stores inventories locally. Pro offers optional private iCloud sync. The app does not require a StockScan account or use advertising or tracking services. This policy covers the app, website and support.',
 'privacy_sections':[
  ['1. Controller',CONTACT],
  ['2. Inventory and master data','<p>StockScan processes the item codes, EANs, names, quantities, units, comments, mappings and timestamps you enter or import. This includes inventory lists, fixed checklists, count and review states, completed inventories and templates. Data is stored locally using SwiftData. Imported product, manufacturer and supplier master data stays on each device.</p>'],
  ['3. Optional private iCloud sync','<p>If you explicitly enable Pro sync, inventories sync through Apple CloudKit in your iCloud account’s private database across your own Apple devices. StockScan does not operate its own inventory server. Local data remains the foundation. Imported master data does not sync.</p><p>You can pause sync and separately delete the cloud copy using the provided control. Subscription expiry or a connection issue does not delete local data. Removing the app does not automatically delete the cloud copy. Apple’s processing is also governed by your iCloud settings and <a href="https://www.apple.com/legal/privacy/">Apple’s privacy policy</a>.</p>'],
  ['4. Purchases and Apple Family Sharing','<p>Purchases, restores and subscription entitlements are handled natively through Apple StoreKit. Apple processes payments; the developer does not receive payment details. Family Sharing shares Pro entitlement, not inventories or your private iCloud database. StockScan does not use a third-party subscription service.</p>'],
  ['5. Camera, Apple Watch and Live Activities','<p>Camera access is used for barcode recognition. Camera photos are not saved or sent to the developer. Selected count data is exchanged between iPhone and a paired Apple Watch using WatchConnectivity. Pending Watch counts remain queued until confirmed when disconnected. Live Activities display inventory progress on your device’s system surfaces.</p>'],
  ['6. Intelligent import assistance','<p>On supported devices, intelligent column recognition can use Apple Intelligence when available. The app’s column recognition runs on the device. Standard recognition remains available as an alternative. StockScan does not send spreadsheets to a developer-operated AI service.</p>'],
  ['7. Exports, deletion and device backups','<p>You choose where to send CSV or XLSX files through the system share sheet. Selected destination apps or services have their own privacy terms. Local inventories can be deleted in the app. Removing the app removes its local data; save anything you need first. A personal device backup may include app data according to your Apple settings. Device backups and optional CloudKit sync are separate features.</p>'],
  ['8. Support and voluntary diagnostic reports','<p>If you email us, we process your sender address and the contents you provide to answer your request. A technical diagnostic report is created and shared only when you choose. It contains technical app and device information, settings states and aggregate database counts. Review it before sending and only share necessary information.</p>'],
  ['9. This website','<p>This website is hosted on GitHub Pages. GitHub processes connection and request data needed to serve pages, such as IP address, browser information and request time. See <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub’s privacy statement</a> for processing and international transfer information.</p><p>Our website does not embed analytics tools, advertising pixels or external fonts and does not itself set cookies. Language selection uses separate pages without browser storage. Opening an external link, such as the App Store, accesses that service.</p>'],
  ['10. Your privacy requests','<p>You can contact us about access, correction, deletion, restriction, portability or objection concerning personal data. Where processing relies on consent, you may withdraw it for the future. You also have the right to complain to a data protection supervisory authority. Inventories stored only locally are managed directly on your device; the developer has no access to their contents.</p>'],
  ['11. Contact','<p>Privacy questions: <a href="mailto:stockscansupport@gmail.com">stockscansupport@gmail.com</a></p>']
 ]
}}

def build_documents():
 for lang,d in DOCS.items():
  c=C[lang];out=ROOT/('en' if lang=='en' else '')
  body=f'<div class="document"><span class="eyebrow">StockScan Support</span><h1>{d["support_title"]}</h1><p class="lead">{d["support_intro"]}</p><div class="faq-list">{faq_html(d["help"]+c["faqs"])}</div><section class="callout contact"><h2>{d["contact_title"]}</h2><p>{d["contact_text"]}</p><a class="text-link" href="mailto:stockscansupport@gmail.com">stockscansupport@gmail.com ↗</a></section></div>'
  (out/'support.html').write_text(page(lang,'support.html',body,'Support – StockScan',d['support_intro']))
  sections=''.join(f'<section><h2>{title}</h2>{text}</section>' for title,text in d['privacy_sections'])
  body=f'<article class="document"><h1>{d["privacy_title"]}</h1><p class="micro">{d["updated"]}</p><div class="callout"><p>{d["privacy_intro"]}</p></div>{sections}</article>'
  (out/'privacy.html').write_text(page(lang,'privacy.html',body,d['privacy_title']+' – StockScan',d['privacy_intro']))
  if lang=='de':
   legal=f'<h1>Impressum</h1><h2>Angaben gemäß § 5 DDG</h2>{CONTACT}<h2>Verantwortlich für den Inhalt</h2><p>Sascha Bommels, Anschrift wie oben.</p><h2>Kontakt</h2><p>E-Mail: <a href="mailto:stockscansupport@gmail.com">stockscansupport@gmail.com</a></p><h2>Haftungsausschluss</h2><p>Die Inhalte dieser Website wurden mit größtmöglicher Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte kann jedoch keine Gewähr übernommen werden.</p><h2>App Store und Marken</h2><p>StockScan ist im Apple App Store erhältlich. Apple Inc. ist nicht Herausgeber dieser App. Apple, iPhone, iPad, Apple Watch und App Store sind Marken von Apple Inc. Andere genannte Marken gehören ihren jeweiligen Rechteinhabern.</p>'
  else:
   legal=f'<h1>Legal notice</h1><h2>Information under § 5 DDG</h2>{CONTACT}<h2>Responsible for content</h2><p>Sascha Bommels, at the address above.</p><h2>Contact</h2><p>Email: <a href="mailto:stockscansupport@gmail.com">stockscansupport@gmail.com</a></p><h2>Disclaimer</h2><p>The content of this website has been prepared with care. No guarantee is given for its accuracy, completeness or timeliness.</p><h2>App Store and trademarks</h2><p>StockScan is available on the Apple App Store. Apple Inc. is not the publisher of this app. Apple, iPhone, iPad, Apple Watch and App Store are trademarks of Apple Inc. Other trademarks belong to their respective owners.</p>'
  (out/'impressum.html').write_text(page(lang,'impressum.html',f'<article class="document">{legal}</article>',c['imprint']+' – StockScan'))
 print('Built localized support, privacy and legal pages.')
if __name__=='__main__':build_documents()
