"""Editable HTML compositions; actual app screenshots stay unchanged."""
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
for lang in ['de','en']:
 title='Deine Inventur.<br>Mit <em>Überblick.</em>' if lang=='de' else 'Your inventory.<br>Clearly <em>in view.</em>'
 sub='Frei zählen. Oder nach Plan.<br>Vom ersten Scan bis zum Bericht.' if lang=='de' else 'Count freely. Or follow a plan.<br>From your first scan to your report.'
 benefit='CSV kostenlos.<br>Excel mit Pro.' if lang=='de' else 'Free CSV.<br>Excel with Pro.'
 cta='Kostenlos im App Store' if lang=='de' else 'Free on the App Store'
 limit='1 aktive Inventur · 100 Artikel · CSV kostenlos' if lang=='de' else '1 active inventory · 100 items · Free CSV'
 for size,width,height in [('square',1080,1080),('story',1080,1920)]:
  html=f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width={width}"><title>StockScan {lang} {size}</title><style>
*{{box-sizing:border-box}}body{{margin:0;width:{width}px;height:{height}px;overflow:hidden;background:#103e31;color:#f5f5ed;font-family:'Avenir Next',Avenir,sans-serif;position:relative}}.mast{{position:absolute;left:76px;top:66px;right:76px;display:flex;align-items:center;gap:16px;padding-bottom:35px;border-bottom:1px solid #426452;font-size:30px;font-weight:600}}.mast img{{width:56px;height:56px;border-radius:13px}}.version{{margin-left:auto;font-size:18px;color:#c0f094;letter-spacing:2px}}h1{{position:absolute;left:76px;top:185px;margin:0;font-size:70px;font-weight:650;line-height:1.13;letter-spacing:-3px}}em{{font-family:Georgia,serif;font-weight:400;color:#c0f094}}.sub{{position:absolute;left:80px;top:388px;font-size:25px;line-height:1.65;color:#c6d7c8;max-width:550px}}.phone{{position:absolute;right:70px;top:254px;width:295px;border:8px solid #0a281e;outline:1px solid #63806c;border-radius:38px;overflow:hidden;box-shadow:0 28px 65px #00140a60;transform:rotate(5deg)}}.phone img{{display:block;width:100%}}.benefit{{position:absolute;left:80px;top:594px;font-size:29px;line-height:1.35;font-weight:600}}.cta{{position:absolute;left:80px;top:738px;padding:20px 27px;background:#c0f094;color:#103e31;font-size:23px;font-weight:650;border-radius:11px}}.devices{{position:absolute;left:80px;bottom:100px;font-size:20px;color:#c6d7c8}}.limit{{position:absolute;left:80px;bottom:61px;font-size:16px;color:#c6d7c8}}.story h1{{top:229px;font-size:101px;line-height:1.06;letter-spacing:-4px}}.story .sub{{top:487px;font-size:32px;max-width:890px}}.story .phone{{top:680px;right:325px;width:430px;border-width:10px;border-radius:47px;transform:rotate(0)}}.story .benefit{{top:1130px;left:630px;background:#c0f094;color:#103e31;padding:24px 28px;border-radius:14px;font-size:27px;transform:rotate(4deg);z-index:2}}.story .cta{{top:1665px;left:335px;font-size:27px}}.story .devices{{left:0;right:0;bottom:126px;text-align:center;font-size:24px}}.story .limit{{left:0;right:0;bottom:77px;text-align:center;font-size:19px}}
</style></head><body class="{size}"><div class="mast"><img src="../../img/icon.png" alt="">StockScan<span class="version">1.4</span></div><h1>{title}</h1><p class="sub">{sub}</p><div class="phone"><img src="../../assets/screens/iphone-{lang}-01-inventory.webp" alt="StockScan"></div><div class="benefit">{benefit}</div><div class="cta">{cta}</div><div class="devices">iPhone · iPad · Apple Watch</div><div class="limit">{limit}</div></body></html>'''
  (ROOT/'marketing/source'/f'{size}-{lang}.html').write_text(html)
print('Created four editable marketing compositions.')
